version: '3.9'

services:

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./config/caddy:/etc/caddy
    ports:
      - 80:80
      - 443:443

  varnish:
    image: varnish:alpine
    container_name: varnish
    restart: unless-stopped
    volumes:
     - ./config/varnish/default.vcl:/etc/varnish/default.vcl

  ghost:
    image: ghost:alpine
    container_name: ghost
    depends_on:
      - ghost-db
    restart: unless-stopped
    environment:
      database__client: mysql
      database__connection__host: ${MYSQL_HOST}
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: ${URL_GHOST}
    volumes:
      - ./data/ghost:/var/lib/ghost/content

  ghost-db:
    container_name: ghost-db
    #for arm64 use oracle tag
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/ghost-db:/var/lib/mysql
